"""
HTML report generator with inline SVG charts.

Generates a single self-contained HTML file with:
- Inline CSS (no external deps)
- SVG charts generated in Python
- Print-friendly @media print styles
- Provenance badges on non-official data
- Table of contents with anchors
"""
from __future__ import annotations

import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any

OUTPUT_DIR = Path(__file__).parent.parent / "output"


def generate_html_report(
    report_data: dict[str, Any],
    language: str = "en",
    output_path: Path | None = None,
) -> dict[str, str]:
    """Generate complete HTML report from structured data.

    Returns dict with file paths written:
    - report.html
    - report_data.json
    - sources.txt
    - contacts.csv
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    uni_slug = report_data.get("university", "report").lower().replace(" ", "_")
    out_dir = output_path or OUTPUT_DIR / uni_slug
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write report_data.json (source of truth)
    data_path = out_dir / "report_data.json"
    data_path.write_text(json.dumps(report_data, indent=2, ensure_ascii=False, default=str), encoding="utf-8")

    # Generate HTML
    html_content = _build_html(report_data, language)
    html_path = out_dir / "report.html"
    html_path.write_text(html_content, encoding="utf-8")

    # Generate sources.txt
    sources = report_data.get("sources", [])
    sources_path = out_dir / "sources.txt"
    sources_path.write_text("\n".join(s.get("url", "") for s in sources if s.get("url")), encoding="utf-8")

    # Generate contacts.csv
    contacts = report_data.get("contacts", [])
    csv_path = out_dir / "contacts.csv"
    _write_contacts_csv(contacts, csv_path)

    return {
        "report_html": str(html_path),
        "report_data_json": str(data_path),
        "sources_txt": str(sources_path),
        "contacts_csv": str(csv_path),
    }


def _build_html(data: dict[str, Any], language: str) -> str:
    """Build the complete HTML document."""
    uni_name = data.get("university", "University Report")
    sections = []

    # Build sections from available data
    if "overview" in data:
        sections.append(_section_overview(data["overview"]))
    if "rankings" in data:
        sections.append(_section_rankings(data["rankings"]))
    if "international" in data:
        sections.append(_section_international(data["international"]))
    if "english_requirements" in data:
        sections.append(_section_english(data["english_requirements"]))
    if "faculty" in data:
        sections.append(_section_faculty(data["faculty"]))
    if "opportunities" in data:
        sections.append(_section_opportunities(data["opportunities"]))
    if "career_outcomes" in data:
        sections.append(_section_career(data["career_outcomes"]))
    if "alumni" in data:
        sections.append(_section_alumni(data["alumni"]))
    if "community" in data:
        sections.append(_section_community(data["community"]))
    if "visa_pathways" in data:
        sections.append(_section_visa(data["visa_pathways"]))
    if "application" in data:
        sections.append(_section_application(data["application"]))

    # Table of contents
    toc = _build_toc(sections)

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""<!DOCTYPE html>
<html lang="{language}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(uni_name)} — Research Report</title>
<style>
{_get_css()}
</style>
</head>
<body>
<header>
<h1>{html.escape(uni_name)}</h1>
<p class="subtitle">Undergraduate Application Research Report</p>
<p class="meta">Generated: {generated_at} | Data sources: College Scorecard, ORCID, Semantic Scholar, web search</p>
</header>
<nav id="toc">
<h2>Contents</h2>
{toc}
</nav>
<main>
{"".join(s["html"] for s in sections)}
</main>
<footer>
<p>Generated by US College Research Tool. Data has provenance markers — verify non-official sources independently.</p>
</footer>
</body>
</html>"""


def _get_css() -> str:
    """Return the full CSS for the report."""
    return """
:root {
    --bg: #ffffff;
    --text: #1a1a1a;
    --muted: #6b7280;
    --border: #e5e7eb;
    --accent: #2563eb;
    --accent-light: #eff6ff;
    --warning: #f59e0b;
    --warning-bg: #fffbeb;
    --danger: #ef4444;
    --success: #10b981;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
    line-height: 1.6;
    color: var(--text);
    max-width: 900px;
    margin: 0 auto;
    padding: 2rem 1.5rem;
    font-size: 14px;
}
header { margin-bottom: 2rem; border-bottom: 2px solid var(--accent); padding-bottom: 1rem; }
h1 { font-size: 1.8rem; font-weight: 700; }
.subtitle { color: var(--muted); font-size: 1rem; margin-top: 0.25rem; }
.meta { color: var(--muted); font-size: 0.8rem; margin-top: 0.5rem; }
nav#toc { background: var(--accent-light); padding: 1rem 1.5rem; border-radius: 8px; margin-bottom: 2rem; }
nav#toc h2 { font-size: 1rem; margin-bottom: 0.5rem; }
nav#toc ul { list-style: none; columns: 2; column-gap: 2rem; }
nav#toc li { margin-bottom: 0.25rem; }
nav#toc a { color: var(--accent); text-decoration: none; font-size: 0.85rem; }
section { margin-bottom: 2.5rem; page-break-inside: avoid; }
h2 { font-size: 1.3rem; border-bottom: 1px solid var(--border); padding-bottom: 0.3rem; margin-bottom: 1rem; }
h3 { font-size: 1.05rem; margin: 1rem 0 0.5rem; }
table { width: 100%; border-collapse: collapse; margin: 0.75rem 0; font-size: 0.85rem; }
th, td { padding: 0.4rem 0.6rem; text-align: left; border-bottom: 1px solid var(--border); }
th { background: var(--accent-light); font-weight: 600; }
tr:nth-child(even) td { background: #f9fafb; }
.badge { display: inline-block; font-size: 0.7rem; padding: 0.1rem 0.4rem; border-radius: 3px; font-weight: 600; vertical-align: middle; margin-left: 0.3rem; }
.badge-official { background: #dcfce7; color: #166534; }
.badge-unofficial { background: var(--warning-bg); color: #92400e; }
.badge-estimated { background: #fef2f2; color: #991b1b; }
.badge-high { background: #dcfce7; color: #166534; }
.badge-medium { background: #fef9c3; color: #854d0e; }
.badge-low { background: #fef2f2; color: #991b1b; }
.alert { padding: 0.75rem 1rem; border-radius: 6px; margin: 0.75rem 0; font-size: 0.85rem; }
.alert-warning { background: var(--warning-bg); border-left: 3px solid var(--warning); }
.alert-info { background: var(--accent-light); border-left: 3px solid var(--accent); }
.chart-container { margin: 1rem 0; }
svg { max-width: 100%; height: auto; }
ul, ol { padding-left: 1.5rem; margin: 0.5rem 0; }
li { margin-bottom: 0.25rem; }
a { color: var(--accent); }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.75rem; }

@media print {
    body { max-width: none; padding: 0; font-size: 11px; }
    nav#toc { display: none; }
    section { page-break-inside: avoid; }
    h2 { page-break-after: avoid; }
    table { page-break-inside: avoid; }
    a::after { content: " (" attr(href) ")"; font-size: 0.7em; color: var(--muted); }
    .alert { border: 1px solid var(--border); }
}
"""


def _build_toc(sections: list[dict[str, str]]) -> str:
    """Build table of contents from sections."""
    items = []
    for s in sections:
        items.append(f'<li><a href="#{s["id"]}">{html.escape(s["title"])}</a></li>')
    return f"<ul>{''.join(items)}</ul>"


def _section_overview(data: dict[str, Any]) -> dict[str, str]:
    """Institutional overview section."""
    metrics = data.get("metrics", {})
    rows = []
    for key, m in metrics.items():
        if not isinstance(m, dict) or m.get("value") is None:
            continue
        val = m["value"]
        label = m.get("label", key)
        if isinstance(val, float) and val < 1:
            display = f"{val * 100:.1f}%"
        elif isinstance(val, (int, float)) and val > 1000:
            display = f"${val:,.0f}"
        else:
            display = str(val)
        rows.append(f"<tr><td>{html.escape(label)}</td><td><strong>{display}</strong></td></tr>")

    # Net price by income chart
    chart = _chart_net_price_by_income(metrics)

    return {
        "id": "overview",
        "title": "Institutional Overview",
        "html": f"""<section id="overview">
<h2>Institutional Overview</h2>
<table><thead><tr><th>Metric</th><th>Value</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table>
{chart}
<div class="alert alert-warning">Data from College Scorecard (U.S. Department of Education). Has 2-3 year lag from current year.</div>
</section>""",
    }


def _section_rankings(data: dict[str, Any]) -> dict[str, str]:
    return {"id": "rankings", "title": "Rankings", "html": f'<section id="rankings"><h2>Rankings</h2><p>See report_data.json for ranking details and search queries.</p></section>'}


def _section_international(data: dict[str, Any]) -> dict[str, str]:
    items = []
    d = data.get("data", {})
    if "need_blind_international" in d:
        policy = d["need_blind_international"]
        val = policy.get("value", "unknown") if isinstance(policy, dict) else policy
        badge = _provenance_badge(policy) if isinstance(policy, dict) else ""
        items.append(f"<tr><td>Need-blind for internationals?</td><td><strong>{val}</strong> {badge}</td></tr>")
    if "aid_first_year_only" in d:
        policy = d["aid_first_year_only"]
        val = policy.get("value", "unknown") if isinstance(policy, dict) else policy
        badge = _provenance_badge(policy) if isinstance(policy, dict) else ""
        alert = '<div class="alert alert-warning">Aid only available at freshman admission. Cannot apply later.</div>' if val else ""
        items.append(f"<tr><td>Aid only at first year?</td><td><strong>{val}</strong> {badge}</td></tr>")

    return {
        "id": "international",
        "title": "International Admissions",
        "html": f"""<section id="international">
<h2>International Admissions</h2>
<table><thead><tr><th>Policy</th><th>Status</th></tr></thead>
<tbody>{"".join(items)}</tbody></table>
{alert if 'alert' in dir() else ''}
</section>""",
    }


def _section_english(data: dict[str, Any]) -> dict[str, str]:
    return {"id": "english", "title": "English & Test Requirements", "html": '<section id="english"><h2>English & Test Requirements</h2><p>See report_data.json for detailed requirements.</p></section>'}


def _section_faculty(data: dict[str, Any]) -> dict[str, str]:
    professors = data if isinstance(data, list) else data.get("professors", [])
    rows = []
    for p in professors[:20]:
        name = p.get("name", "")
        title = p.get("title", "")
        email = p.get("email", "")
        score = p.get("relevance_score", "")
        email_link = f'<a href="mailto:{email}">{email}</a>' if email else ""
        rows.append(f"<tr><td><strong>{html.escape(name)}</strong></td><td>{html.escape(title)}</td><td>{email_link}</td><td>{score}</td></tr>")

    return {
        "id": "faculty",
        "title": "Faculty & Research",
        "html": f"""<section id="faculty">
<h2>Faculty & Research</h2>
<table><thead><tr><th>Name</th><th>Title</th><th>Email</th><th>Relevance</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table>
</section>""",
    }


def _section_opportunities(data: dict[str, Any]) -> dict[str, str]:
    items = []
    if isinstance(data, dict):
        for category, opps in data.items():
            if not isinstance(opps, list):
                continue
            items.append(f"<h3>{html.escape(category)}</h3><ul>")
            for o in opps:
                name = o.get("name", "")
                desc = o.get("description", "")
                url = o.get("source_url", "")
                link = f' — <a href="{url}">source</a>' if url else ""
                items.append(f"<li><strong>{html.escape(name)}</strong>: {html.escape(desc)}{link}</li>")
            items.append("</ul>")

    return {"id": "opportunities", "title": "Opportunities", "html": f'<section id="opportunities"><h2>Opportunities</h2>{"".join(items)}</section>'}


def _section_career(data: dict[str, Any]) -> dict[str, str]:
    return {"id": "career", "title": "Career Outcomes", "html": '<section id="career"><h2>Career Outcomes</h2><p>See report_data.json for career outcome details.</p></section>'}


def _section_alumni(data: dict[str, Any]) -> dict[str, str]:
    return {"id": "alumni", "title": "Alumni Network", "html": '<section id="alumni"><h2>Alumni Network</h2><p>See report_data.json for alumni data and LinkedIn links.</p></section>'}


def _section_community(data: dict[str, Any]) -> dict[str, str]:
    return {"id": "community", "title": "Country Community", "html": '<section id="community"><h2>Country Community</h2><p>See report_data.json for community details.</p></section>'}


def _section_visa(data: dict[str, Any]) -> dict[str, str]:
    return {"id": "visa", "title": "Visa & Entrepreneurship Pathways", "html": '<section id="visa"><h2>Visa & Entrepreneurship Pathways</h2><p>See report_data.json for visa details.</p></section>'}


def _section_application(data: dict[str, Any]) -> dict[str, str]:
    return {"id": "application", "title": "Application Requirements", "html": '<section id="application"><h2>Application Requirements</h2><p>See report_data.json for application details.</p></section>'}


# --- SVG Chart Generators ---

def _chart_net_price_by_income(metrics: dict[str, Any]) -> str:
    """Generate SVG bar chart of net price by income bracket."""
    brackets = [
        ("$0-30k", "net_price_0_30k"),
        ("$30-48k", "net_price_30_48k"),
        ("$48-75k", "net_price_48_75k"),
        ("$75-110k", "net_price_75_110k"),
        ("$110k+", "net_price_110k_plus"),
    ]
    values = []
    for label, key in brackets:
        m = metrics.get(key, {})
        val = m.get("value") if isinstance(m, dict) else None
        values.append((label, val))

    # Filter out None values
    valid = [(l, v) for l, v in values if v is not None]
    if not valid:
        return ""

    max_val = max(v for _, v in valid)
    if max_val == 0:
        return ""

    bar_width = 80
    bar_gap = 10
    chart_width = len(valid) * (bar_width + bar_gap) + 60
    chart_height = 200
    max_bar_height = 150

    bars = []
    for i, (label, val) in enumerate(valid):
        x = 50 + i * (bar_width + bar_gap)
        bar_height = (val / max_val) * max_bar_height
        y = chart_height - 30 - bar_height
        bars.append(
            f'<rect x="{x}" y="{y}" width="{bar_width}" height="{bar_height}" fill="#2563eb" rx="3"/>'
            f'<text x="{x + bar_width/2}" y="{y - 5}" text-anchor="middle" font-size="11" fill="#1a1a1a">${val:,.0f}</text>'
            f'<text x="{x + bar_width/2}" y="{chart_height - 10}" text-anchor="middle" font-size="10" fill="#6b7280">{label}</text>'
        )

    # Add sticker price line if available
    sticker = metrics.get("tuition_out_of_state", {})
    sticker_val = sticker.get("value") if isinstance(sticker, dict) else None
    sticker_line = ""
    if sticker_val and sticker_val > max_val:
        max_val = sticker_val
        # Recalculate bars with new max
        bars = []
        for i, (label, val) in enumerate(valid):
            x = 50 + i * (bar_width + bar_gap)
            bar_height = (val / max_val) * max_bar_height
            y = chart_height - 30 - bar_height
            bars.append(
                f'<rect x="{x}" y="{y}" width="{bar_width}" height="{bar_height}" fill="#2563eb" rx="3"/>'
                f'<text x="{x + bar_width/2}" y="{y - 5}" text-anchor="middle" font-size="11" fill="#1a1a1a">${val:,.0f}</text>'
                f'<text x="{x + bar_width/2}" y="{chart_height - 10}" text-anchor="middle" font-size="10" fill="#6b7280">{label}</text>'
            )
        sticker_y = chart_height - 30 - (sticker_val / max_val) * max_bar_height
        sticker_line = (
            f'<line x1="45" y1="{sticker_y}" x2="{chart_width - 10}" y2="{sticker_y}" stroke="#ef4444" stroke-width="1.5" stroke-dasharray="5,3"/>'
            f'<text x="{chart_width - 10}" y="{sticker_y - 5}" text-anchor="end" font-size="10" fill="#ef4444">Sticker: ${sticker_val:,.0f}</text>'
        )

    return f"""<div class="chart-container">
<h3>Net Price by Family Income</h3>
<svg width="{chart_width}" height="{chart_height}" viewBox="0 0 {chart_width} {chart_height}">
{"".join(bars)}
{sticker_line}
</svg>
<p style="font-size:0.75rem;color:#6b7280;">Source: College Scorecard. Reflects domestic students with financial aid. International aid varies.</p>
</div>"""


def _provenance_badge(data: dict[str, Any]) -> str:
    """Generate provenance badge HTML."""
    source_type = data.get("source_type", "unknown")
    confidence = data.get("confidence", "low")

    type_class = {
        "official": "badge-official",
        "unofficial": "badge-unofficial",
        "estimated": "badge-estimated",
    }.get(source_type, "badge-estimated")

    conf_class = {
        "high": "badge-high",
        "medium": "badge-medium",
        "low": "badge-low",
    }.get(confidence, "badge-low")

    badges = f'<span class="badge {type_class}">{source_type}</span>'
    if confidence != "high":
        badges += f' <span class="badge {conf_class}">{confidence} confidence</span>'
    return badges


def _write_contacts_csv(contacts: list[dict[str, str]], path: Path) -> None:
    """Write contacts to CSV."""
    if not contacts:
        path.write_text("name,role,email,linkedin,orcid,priority,university\n", encoding="utf-8")
        return

    lines = ["name,role,email,linkedin,orcid,priority,university"]
    for c in contacts:
        row = [
            c.get("name", ""),
            c.get("role", ""),
            c.get("email", ""),
            c.get("linkedin", ""),
            c.get("orcid", ""),
            c.get("priority", ""),
            c.get("university", ""),
        ]
        lines.append(",".join(f'"{v}"' for v in row))
    path.write_text("\n".join(lines), encoding="utf-8")
